spring:
  application:
    name: service-project


  datasource:
    url: jdbc:mysql://222.85.147.249:3306/niit_smartkids?serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1Hblsqt$
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/niit_samrtkids?useUnicode=true&amp;characterEncoding=utf8&amp;serverTimezone=GMT%2B8&amp;useSSL=false
#    username: root
#    password: etoak


server:
  port: 8087

  datasource:
    url: jdbc:mysql://localhost:3306/niit?serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 511946225

  #  datasource:
  #    url: jdbc:mysql://localhost:3306/niit_samrtkids?serverTimezone=GMT
  #    driver-class-name: com.mysql.jdbc.Driver
  #    username: root
  #    password: etoak
  application:
    name: service-project
  cloud:
    config:
      uri: http://127.0.0.1:8888

mybatis:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

# 分页查询配置
pagehelper:
  #  数据库名
  helperDialect: mysql
  #  true->pageNum小于1会查询第一页，如果pageNum大于pageSize会查询最后一页
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

