server:
  port: 8084
  application:
    name: service-uploader
  cloud:
    config:
      uri: http://127.0.0.1:8888

eureka:
  instance:
     prefer-ip-address: true
  client:
    serviceUrl:
        efaultZone: http://127.0.0.1:8761/eureka/
spring:
  resources:
     static-locations: classpath:/static,file:C:/Users/Administrator/Desktop/upload/attachment
  http:
     multipart:
       max-file-size: 5Mb
  mvc:
     async:
        request-timeout: 20000
  application:
    name: service-uploader
xin:
   uploader:
     image-path: C:/upload/image
     common-file-path: C:/upload/file
     attachment-path: C:/upload/attachment
     child-path-strategy: hour

