server:
  port: 8761

spring:
  application:
    name: cloud-eureka-server
  output:
    ansi:
      enabled: always
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
