spring:
  application:
    name: service-lms
  jackson:
    date-format: yyyy-MM-dd  HH:mm:ss
    time-zone: GMT+8

  datasource:
    url: jdbc:mysql://222.85.147.249:3306/niit_smartkids?serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1Hblsqt$

server:
  port: 8883


  application:
    name: service-lms
  cloud:
    config:
      uri: http://127.0.0.1:8888

mybatis:
  mapper-locations: classpath:mapping/*.xml

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

# 分页查询配置
pagehelper:
  #  数据库名
  helperDialect: mysql
  #  true->pageNum小于1会查询第一页，如果pageNum大于pageSize会查询最后一页
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#upload:
#  file:
#    maxsize: 104857600
#    url: http://localhost/test