spring:
  application:
    name: service-bbs
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb

  datasource:
    url: jdbc:mysql://222.85.147.249:3306/niit_smartkids?serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1Hblsqt$

server:
  port: 8880


  application:
    name: service-bbs
  cloud:
    config:
      uri: http://127.0.0.1:8888

mybatis:
  mapper-locations: classpath:mapping/*.xml

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
