spring:
  application:
    name: service-bbs
  http:
      multipart:
        max-file-size: 50Mb
        max-request-size: 50Mb

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.178.227.169:3306/niit_samrtkids?useUnicode=true&amp;characterEncoding=utf8&amp;serverTimezone=GMT%2B8&amp;useSSL=false
    username: smartkids
    password: niit1234

server:
  port: 8880

  datasource:
    url: jdbc:mysql://118.178.227.169:3306/niit_samrtkids?serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: smartkids
    password: niit1234
  application:
    name: service-bbs
  cloud:
    config:
      uri: http://127.0.0.1:8888

mybatis:
  mapper-locations: classpath:mapping/*.xml

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
